repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.260"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/ambv/black
    rev: "23.3.0"
    hooks:
      - id: black
        pass_filenames: false
        args:
          - xonsh_parser
          - tests
        language_version: python3.8


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v2.1.1"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow
