[tool.ruff]
extend-select = ["B", "I"]
# ruff ignore file "xonsh_parser/ply/yacc.py"
[tool.ruff.per-file-ignores]
"xonsh_parser/ply/yacc.py" = [
    "F401", # [*] `ast.Or` imported but unused
    "E501", # Line too long (98 > 88 characters)
    "I001", # [*] Import block is un-sorted or un-formatted
    "E731", #  [*] Do not assign a `lambda` expression, use a `def`
    "B007", # Loop control variable `rule` not used within loop body
    "B904", # Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
]
"xonsh_parser/xast.py" = [
    "F401", # [*] `ast.Add` imported but unused
]
"xonsh_parser/parsers/*.py" = [
    "E501", # Line too long (121 > 88 characters)
]
"xonsh_parser/*.py" = [
    "E741" # Ambiguous variable name: `l` -- todo: fix this
]
"xonsh_parser/tokenize.py" = [
    "F821", # Undefined name `strstart`
    "F841", # [*] Local variable `strstart` is assigned to but never used
    "B904", # Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
]


[tool.pytest.ini_options]
addopts = ""


[tool.hatch]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
source = "regex_commit"
commit_extra_args = ["-e"]
path = "xonsh_parser/__init__.py"


[tool.pdm]
[project.optional-dependencies]
lint = [
    "black",
    "mypy",
    "ruff",]
test = [
    "pytest",
    "pytest-cov",
    ]
docs = [
    "mkdocs-material",
    "mkdocstrings[python]",
]
profile = [
    "asv>=0.5.1",
    "virtualenv>=20.21.0",
    "pympler>=1.0.1",
]

[tool.hatch.envs.default.scripts]
test = "pytest"
test-cov-xml = "pytest --cov=xonsh_parser/ --cov-report=term-missing --cov-report=xml"
lint = [
  "black .",
  "ruff --fix .",
  "mypy xonsh_parser/",
]
lint-check = [
  "black --check .",
  "ruff .",
  "mypy xonsh_parser/",
]
bench = [
    "asv run --python=same --show-stderr", # quickly run benchmarks
]
bench-view = [
    "asv publish",
    "asv preview",
]
docs-serve = "mkdocs serve"
docs-build = "mkdocs build"

[build-system]
requires = ["hatchling", "hatch-regex-commit"]
build-backend = "hatchling.build"

[project]
name = "xonsh-parser"
authors = [
  { name = "xonsh-parser", email = "jnoortheen@gmail.com" }
]
description = "Xonsh parser using PLY"
readme = "README.md"
dynamic = ["version"]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
]
requires-python = ">=3.9"
dependencies = [
]

[project.urls]
Documentation = "https://jnoortheen.github.io/xonsh-parser/"
Source = "https://github.com/jnoortheen/xonsh-parser"

[tool.black]
# exclude extend to file "xonsh_parser/ply/yacc.py"
extend-exclude = ".+ply/.+.py"
