version: '3'
tasks:
  generate:
    cmds:
      - python3 peg_parser/tasks/generate_parser.py
    generates:
      - peg_parser/parser/parser.py
    sources:
      - peg_parser/parser/xonsh.gram
      - peg_parser/parser/*.py
      - pegen/*.py

  profile:
    cmds:
      - python peg_parser/tasks/profile_mem.py tee "logs/xonsh-parser-$(date "+%Y%m%d-%H%M%S").log"

  ply-add:
    cmds:
      - git subtree add --prefix=ply --squash

  cpy-pegen-add:
    cmds:
      - git fetch https://github.com/python/cpython.git main:cpython-main --no-tags --depth 1
      - git read-tree --prefix=pegen -u cpython-main:Tools/peg_generator/pegen

  pegen-add:
    cmds:
      - git fetch https://github.com/we-like-parsers/pegen.git main:tmp-pegen-main --no-tags --depth 1
      - git show tmp-pegen-main:data/python.gram > .local/python.gram
      - git read-tree --prefix=pegen -u tmp-pegen-main:src/pegen

  test:
    deps:
      - generate
    cmds:
      - python -m pytest {{.CLI_ARGS}}
    sources:
      - '**/*.py'

#pegen-update:
#    ## In future, you can merge in additional changes as follows: - https://stackoverflow.com/questions/23937436/add-subdirectory-of-remote-repo-with-git-subtree
#    git checkout gitgit/master
#    #$ git subtree split -P contrib/completion -b temporary-split-branch
#    #$ git checkout master
#    #$ git subtree merge --squash -P third_party/git-completion temporary-split-branch
#    ## Now fix any conflicts if you'd modified third_party/git-completion.
#    #$ git branch -D temporary-split-branch
