# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  add-ply-subtree:
    cmds:
      - git subtree add --prefix=ply --squash https://github.com/dabeaz/ply.git master
  add-pegen-subtree:
    cmds:
      - git subtree add --prefix=pegen --squash

  asv:
    cmds:
      - asv run
