version: '3'
tasks:
  generate:
    cmds:
      - python3 tasks/generate_parser.py
    generates:
      - peg_parser/parser.py
    sources:
      - tasks/xonsh.gram
      - peg_parser/*.py
      - pegen/*.py

  profile:
    cmds:
      - python tasks/profile_mem.py tee "logs/xonsh-parser-$(date "+%Y%m%d-%H%M%S").log"

  ply-add:
    cmds:
      - git subtree add --prefix=ply --squash

  pegen-add:
    cmds:
      - git fetch https://github.com/we-like-parsers/pegen.git main:tmp-pegen-main --no-tags --depth 1
      - git show tmp-pegen-main:data/python.gram > .local/python.gram
      - git read-tree --prefix=pegen -u tmp-pegen-main:src/pegen

  test:
    deps:
      - generate
    cmds:
      - python -m pytest {{.CLI_ARGS}}
    sources:
      - '**/*.py'

  wtest:
    cmds:
      - watchexec -e py,gram --clear -- task test -- --ff -x -vv --testmon

  bench:
    cmds:
      - asv run --python=same --show-stderr

  bench-view:
    cmds:
      - asv publish
      - asv preview