version: '3'
tasks:
  generate-meta:
    cmds:
      - git checkout pegen/grammar_parser.py
      - python3 -m pegen pegen/metagrammar.gram -o pegen/grammar_parser.py
      - ruff format pegen/grammar_parser.py
  generate:
    cmds:
      - python3 tasks/generate_parser.py
      - ruff check --fix peg_parser/parser.py
      - ruff format peg_parser/parser.py
      - scc peg_parser/parser.py --uloc
      - ls -lh peg_parser/parser.py
    generates:
      - peg_parser/parser.py
    sources:
      - tasks/*.py
      - tasks/*.gram
      - peg_parser/*.py
      - pegen/*.py

  check-duplicates:
    cmds:
      - pylint --enable=R0801 --disable=W,C,R0916,R0911,R0912,R0904  --min-similarity-lines=1 peg_parser/parser.py
      - jscpd peg_parser/parser.py

  profile:
    cmds:
      - mkdir -p .local/logs
      - asv run --python=same --show-stderr | tee -a {{.LOG_FILE}}
      - python tasks/profile_mem.py | tee -a {{.LOG_FILE}}
      - python tasks/simple.py | tee -a {{.LOG_FILE}}
      - asv profile --python=same benchmarks.PeakMemSuite.peakmem_parser_large_file | tee -a {{.LOG_FILE}}
    vars:
      LOG_FILE:
        sh: echo ".local/logs/xonsh-parser-$(date "+%Y%m%d-%H%M%S").$(git rev-parse --short HEAD).log"

  ply-add:
    cmds:
      - git subtree add --prefix=ply --squash

  pegen-add:
    cmds:
      - git fetch https://github.com/we-like-parsers/pegen.git main:tmp-pegen-main --no-tags --depth 1
      - git show tmp-pegen-main:data/python.gram > .local/python.gram
      - git read-tree --prefix=pegen -u tmp-pegen-main:src/pegen

  test:
    deps:
      - generate
    cmds:
      - python -m pytest {{.CLI_ARGS}}
    sources:
      - '**/*.py'

  wtest:
    cmds:
      - watchexec -e py,gram --clear -- task test -- --ff -x -vv --testmon

  bench:
    cmds:
      - asv run "main^!" -v
      - asv publish
      - asv preview

  memray:
    cmds:
      - pytest --memray
  mypy1:
    cmds:
      - mypy peg_parser
  mypy:
    cmds:
      - watchexec -e py,toml,gram --clear -- task generate mypy1

  mypyc:
    cmds:
      - pip install setuptools_scm wheel
      - env COMPILE_WITH_MYPYC=1 pip install -e . --no-build-isolation
    sources:
      - peg_parser/subheader.py
      - peg_parser/toke*.py

  clean:
    cmds:
      - find peg_parser -name "*.so" -delete -print

  release:
    # https://python-semantic-release.readthedocs.io/en/latest/commands.html
    cmds:
      - semantic-release version --no-vcs-release {{.CLI_ARGS}}
      - git push --follow-tags
